apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysma.name" . }}-config
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version |replace "+" "_" }}
    release : {{ .Release.Name}}
    heritage: {{ .Release.Service}}
data:
  envoy.yaml: |-
    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: "0.0.0.0"
          port_value: {{ .Values.service.adminPort }}
    static_resources:
      listeners:
      - name: listener_http
        address:
          socket_address:
            address: "0.0.0.0"
            port_value: 80
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: auto
              stat_prefix: ingress_http
              route_config:
                virtual_hosts:
                - name: backend
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    redirect:
                      path_redirect: "/"
                      https_redirect: true
              http_filters:
              - name: envoy.router
      - name: listener_https
        address:
          socket_address:
            address: "0.0.0.0"
            port_value: {{ .Values.service.port }}
        filter_chains:
          - filters:
            - name: envoy.http_connection_manager
              config:
                access_log:
                - name: envoy.file_access_log
                  config:
                    path: "/dev/stdout"
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  virtual_hosts:
                  - name: backend
                    domains: ["*"]
                    routes:
                    - match:
                        prefix: "/"
                      route:
                        cluster: {{ include "mysma.name" . }}
                http_filters:
                - name: envoy.router
            tls_context:
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: "/certs/tls.crt"
                    private_key:
                      filename: "/certs/tls.key"
      clusters:
        - name: {{ include "mysma.name" . }}
          connect_timeout: 0.25s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          hosts:
            - socket_address:
                address: "0.0.0.0"
                port_value: {{ .Values.sma.config.server.port }}
