{{- if .Values.sma.config.ingress.enabled -}}
{{- $ingressPath := .Values.sma.config.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mysma
  labels:
    app: mysma
{{- with .Values.sma.config.ingress.annotations }}
  annotations:
{{ toYaml . | indent 3 }}
{{- end }}
    #kubernetes.io/ingress.class: nginx-public
    #ingress.kubernetes.io/force-ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: mysma
          servicePort: 8080
        #path: {{ .Values.sma.config.ingress.path }}
        path: {{ $ingressPath }}
        #path: /sma-envoy/?(.*)
{{- end }}
