apiVersion: v1
kind: Service
metadata:
  name:  {{ .Chart.Name }}
  labels:
    app:  {{ include "mysma.name" . }} 
    #app: mysma
    chart: {{ .Chart.Name }}-{{ .Chart.Version |replace "+" "_" }}
    release : {{ .Release.Name}}
    heritage: {{ .Release.Service}}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/stats/prometheus"
    prometheus.io/port: "{{ .Values.service.adminPort }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    name: {{ .Values.service.name  | trunc 15 }}
  - port: {{ .Values.service.adminPort }}
    targetPort: {{ .Values.service.adminPort }}
    name: {{ .Values.service.name  | trunc 9 }}-admin
  - port: {{ .Values.sma.config.server.port }} 
    targetPort: {{ .Values.sma.config.server.port }} 
    name: mysma 
  selector:
    app:  {{ include "mysma.name" . }} 
    release:  {{ .Release.Name }} 
  #  app.kubernetes.io/name: {{ include "mysma.name" . }}
  #  app.kubernetes.io/instance: {{ .Release.Name }}
