# Default values for mysma.
# This is a YAML-formatted file.
sma:
  deployment:
    replicaCount: 1
    image:
      repository: cafrd.docker.engineering.csu.local:12345/sma
      tag: latest
      #tag: develop-mvp-ef55c059992 
      pullPolicy: IfNotPresent

  service:
    annotations: {}
    type: ClusterIP
    port: 8080

  ingress:
     enabled: true
     annotations:
       kubernetes.io/ingress.class: nginx-public
       nginx.ingress.kubernetes.io/rewrite-target: /$1
       nginx.ingress.kubernetes.io/ssl-redirect: "false"
  resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
  nodeSelector: {}

  tolerations: []

  affinity:
     podAntiAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         - labelSelector:
            matchExpressions:
              - key: "app"
                operator: In
                values:
                - sma
            topologyKey: "kubernetes.io/hostname"
########################################################################################################################
mssql:
  enabled: true
  mssqlUser: sa
  mssqlPassword: P@ssw0rd
